name: render-deploy

on: 
  push:
    branches: main

jobs: 
  deploy:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v2

      ##Upload to docker hub

      - name: set up docker build 
        uses: docker/setup-buildx-action@v1


      - name: Log in to docker hub
        uses: docker/login-action@v1
        with: 
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with: 
          context: .
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/nestjs-backend:1.0


      - name: Deploy to render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with: 
          service-id: ${{secrets.RENDER_SERVICE_ID}}
          api-key: ${{secrets.RENDER_API_KEY}}
          wait-for-success: true
